project:
  type: website

website:
  title: "TucsonCrimeDashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href : data.qmd
        text: Data
        
      - text: Dashboard
        href: dashboard.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

